AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 instance and S3 bucket in eu-north-1

Parameters:
  KeyName:
    Type: String
    Description: Name of an existing EC2 KeyPair to enable SSH access

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02f3416038bdb17fb  # Amazon Linux 2 for eu-north-1
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      VpcId: !Ref DefaultVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  DefaultVPC:
    Type: AWS::EC2::VPC::Id

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "raksha-bucket-${AWS::StackName}-${AWS::Region}"

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref MyEC2Instance
